name: request

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  autorequest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: Run a multi-line script
        run: |
          echo "👊👊👊👊👊👊action begin👊👊👊👊👊👊"
          TZ='Asia/Colombo'; export TZ
          
          if [ "$(curl -sL -w '%{http_code}' https://xdxy-tommgunn.koyeb.app/ -o /dev/null)" = "200" ]; then
            echo ------------success excute curl XDXY-TOMMGUNN-K!!!!!!!------------
          else
            echo "XDXY-TOMMGUNN-K Fail!!!"
          fi
          
      - name: request
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "auto-request"
          git push
          
          sleep 1
          echo -e "\033[33;40m  ($0) ${TIME}: this shell script execution duration: ${SECONDS}s  \033[0m"
          echo "😊😊😊😊😊😊success excute shell😊😊😊😊😊😊"

          
